# Generated by Django 2.1.7 on 2019-03-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя Фамилия автора'),
        ),
    ]
